name: CI
on:
  push:
  pull_request:

jobs:
  test:
    name: cargo test
    runs-on: docker
    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev pkg-config

      - uses: https://github.com/dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - run: cargo test --all-features