[package]
name = "fennel-common"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/w1ltshire/fennel.git"
license = "MIT"
description = "Common package of Fennel game engine providing shared types"

[dependencies]
anyhow = "1.0.100"
async-trait = "0.1.89"
sdl3 = "0.15.1"
